apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2 # Running 2 instances of payment-service
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment
          image: gizoskos/payment-service:latest # Replace with your actual Docker Hub image
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:12345678@postgres-service:5432/booking_db" # Connects to PostgreSQL
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort # Expose externally
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 32002 # Minikube assigns external port
