apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 2 # Running 2 instances of booking-service
  selector:
    matchLabels:
      app: booking-service 
  template:
    metadata:
      labels:
        app: booking-service 
    spec:
      containers:
        - name: booking
          image: gizoskos/booking-service:latest #  Use a real Docker image
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:12345678@postgres-service:5432/booking_db"
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  type: NodePort
  selector:
    app: booking-service 
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32001 # Minikube assigns an external port
